var form = document.createElement('form');
document.body.appendChild(form);
form.method = 'post';
form.action = 'https://l-tike.com/st1/jow9a4e9q6a4bm69le4e';
var input = document.createElement('input');
input.type = 'hidden';
input.name = 'CERK';
input.value = '047dccd739afe68ef3a2db79a02b5199';
form.appendChild(input);
form.submit();
