var form = document.createElement('form');
document.body.appendChild(form);
form.method = 'post';
form.action = 'https://l-tike.com/st1/3mikseocy9stpu5smbxf';
var input = document.createElement('input');
input.type = 'hidden';
input.name = 'CERK';
input.value = '19e6a10c1f51659fd9cddff6cda00ff2';
form.appendChild(input);
form.submit();
